import React from "react";

export const metadata = {
  title: "About",
  description: "Generated by create next app",
};

const AboutPage = () => {
  return (
    <div>
      <p>about page</p>
    </div>
  );
};

export default AboutPage;
