import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/navbar/NavBar.jsx";
import Footer from "@/components/Footer.jsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: {
    default: "Nextjs super-app",
    template: "%s | super-app",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-h-[100vh] w-full flex flex-col justify-between">
          <NavBar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
