import PostCard from "@/components/PostCard.jsx";
import { getPosts } from "@/lib/data.js";
import React from "react";

export const metadata = {
  title: "Blog",
  description: "Generated by create next app",
};

// --- AVEC UNE API
const getData = async () => {
  const result = await fetch("http://localhost:3000/api/posts", {
    cache: "no-store",
  });
  if (!result.ok) {
    throw new Error("Erreur");
  }

  return result.json();
};

const blogPage = async () => {
  //--- AVEC UNE API
  const posts = await getData();

  //--- SANS API
  // const posts = await getPosts();

  return (
    <div
      className="p-10 px-20 flex gap-2 flex-wrap justify-satart
    "
    >
      {posts &&
        posts?.map((post, index) => <PostCard post={post} key={index} />)}
    </div>
  );
};

export default blogPage;
